/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utspemvis1;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnGas = new javax.swing.JButton();
        rdKertas = new javax.swing.JRadioButton();
        rdBatu = new javax.swing.JRadioButton();
        rdGunting = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnGas.setBackground(new java.awt.Color(51, 51, 255));
        btnGas.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnGas.setForeground(new java.awt.Color(255, 255, 255));
        btnGas.setText("GAS");
        btnGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGasActionPerformed(evt);
            }
        });

        rdKertas.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdKertas);
        rdKertas.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        rdKertas.setText("Kertas");

        rdBatu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdBatu);
        rdBatu.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        rdBatu.setText("Batu");

        rdGunting.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdGunting);
        rdGunting.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        rdGunting.setText("Gunting");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(rdKertas)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdBatu)
                        .addGap(38, 38, 38)
                        .addComponent(rdGunting)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdKertas)
                    .addComponent(rdBatu)
                    .addComponent(rdGunting))
                .addGap(70, 70, 70)
                .addComponent(btnGas)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGasActionPerformed
        // TODO add your handling code here:
        
        if(buttonGroup1.getSelection() == null){
        JOptionPane.showMessageDialog(null,"Silakan pilih dulu","Peringatan",JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        int pilihanBot = 3;
        int hasilBot;
        
        Random random = new Random();
        
        if(rdBatu.isSelected()){
        hasilBot = random.nextInt(pilihanBot);
            if(hasilBot==0){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Batu \n pilihan Bot Kertas\n Anda Kalah Awowkkowkwok","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }else if(hasilBot==1){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Batu \n pilihan Bot Batu\n Anda Seri","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }else if(hasilBot==2){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Baatu \n pilihan Bot Gunting\n SELAMAT!!! Anda Menang","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }
        }
       if(rdKertas.isSelected()){
        hasilBot = random.nextInt(pilihanBot);
            if(hasilBot==0){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Kertas \n pilihan Bot Kertas\n Anda SERI Awowkkowkwok","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }else if(hasilBot==1){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Kertas \n pilihan Bot Batu\n Selamat Anda Menang","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }else if(hasilBot==2){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Kertas \n pilihan Bot Gunting\n Anda Kalah awowkwokwo","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }
        }
       if(rdGunting.isSelected()){
        hasilBot = random.nextInt(pilihanBot);
            if(hasilBot==0){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Gunting \n pilihan Bot Batu\n Anda Kalah Awowkkowkwok","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }else if(hasilBot==1){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Gunting \n pilihan Bot Gunting\n Anda Seri","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }else if(hasilBot==2){
            JOptionPane.showMessageDialog(null,"Pilihan Anda Gunting \n pilihan Bot Kertas\n SELAMAT!!! Anda Menang","Hasil",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdBatu;
    private javax.swing.JRadioButton rdGunting;
    private javax.swing.JRadioButton rdKertas;
    // End of variables declaration//GEN-END:variables
}
